ln -sf ~/wsl_nvim/airline.vim ~/.config/nvim/airline.vim
ln -sf ~/wsl_nvim/coc-settings.json ~/.config/nvim/coc-settings.json
ln -sf ~/wsl_nvim/coc.vim ~/.config/nvim/coc.vim
ln -sf ~/wsl_nvim/createLink.sh ~/.config/nvim/createLink.sh
ln -sf ~/wsl_nvim/init.vim ~/.config/nvim/init.vim
ln -sf ~/wsl_nvim/lua/kevin/init.lua ~/.config/nvim/lua/kevin/init.lua
ln -sf ~/wsl_nvim/mappings.vim ~/.config/nvim/mappings.vim
ln -sf ~/wsl_nvim/nerdtree.vim ~/.config/nvim/nerdtree.vim
ln -sf ~/wsl_nvim/telescope.vim ~/.config/nvim/telescope.vim
